console.log("this is my first console project");
var first_name="Amogh";
var last_name="Agarwal";
var full_name=first_name.concat(last_name);
console.log(full_name);
var a= 100;
var b= 200;
var add=a+b;
console.log(add);
var sub=a-b;
console.log(sub);
var mul=a*b;
console.log(mul);
var div=a/b;
console.log(div);